<?php $attachedManagers = $this->getManagersCollection(); ?>
<?php if ($attachedManagers->getSize()): ?>
    <div class="panel panel-default">
        <div class="panel-heading"><h2 class="panel-title"><?= $this->__('Your supply manager') ?></h2></div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="info-box">
                        <div class="table-responsive">
                            <table class="table table-hover table-condensed" id="sm-table">
                                <colgroup>
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead>
                                <tr class="first last">
                                    <th><?= $this->__('First Name'); ?></th>
                                    <th><?= $this->__('Last Name'); ?></th>
                                    <th><span class="nobr"><?= $this->__('Email'); ?></span></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody class="font12">
                                <?php foreach ($attachedManagers as $attachment): ?>
                                    <?php if($attachment->getSupplyManagerId()) :?>
                                    <?php $manager = Mage::getModel('customer/customer')->load($attachment->getSupplyManagerId()) ?>
                                        <tr class="first last odd">
                                            <td><span class="nobr"><?= $manager->getFirstname() ?></span></td>
                                            <td><span class="nobr"><?= $manager->getLastname() ?></span></td>
                                            <td class="last"><em><?= $manager->getEmail() ?></em></td>
                                            <td class="last">
                                        <?php
                                        if($attachment->getStatus() == Macopedia_SupplyManager_Model_Attachment::STATUS_PENDING) :?>
                                            <a href="<?php echo($this->getUrl('sm-manager/employee/approve',array('id' => $attachment->getId()))) ?>" class="btn btn-success btn-sm"><?php echo Mage::helper('macopedia_supplymanager')->__("Approve") ?></a>
                                            <a href="<?php echo($this->getUrl('sm-manager/employee/reject',array('id' => $attachment->getId()))) ?>" class="btn btn-danger btn-sm"><?php echo Mage::helper('macopedia_supplymanager')->__("Reject") ?></a>
                                        <?php endif; ?></td>
                                        </tr>
                                    <?php
                                    endif; ?>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                            <script type="text/javascript">decorateTable('sm-table');</script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php else: ?>
<?php endif; ?>